apiVersion: apps/v1
kind: Deployment
metadata:
  name: q9-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: q9-server
  template:
    metadata:
      labels:
        app: q9-server
    spec:
      containers:
      - name: q9-server
        image: hwchiu/sre:q9-server
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: q9-server
spec:
  selector:
    app: q9-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    name: "metrics"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: q9-server-monitor
spec:
  selector:
    matchLabels:
      app: q9-server
  endpoints:
  - port: "metrics"
    path: /metrics
