apiVersion: apps/v1
kind: Deployment
metadata:
  name: q1-app
  labels:
    app: q1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: q1
  template:
    metadata:
      labels:
        app: q1
    spec:
      containers:
      - name: app
        image: hwchiu/sre:q1
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - bash
            - /probe.sh
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 2
        resources:
          requests:
            cpu: 0.1
            memory: "100M"
          limits:
            cpu: 0.1
            memory: "100M"
