apiVersion: apps/v1
kind: Deployment
metadata:
  name: q4-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: q4-server
  template:
    metadata:
      labels:
        app: q4-server
    spec:
      containers:
      - name: q4-server
        image: hwchiu/sre:q4-server
        ports:
        - containerPort: 8080
        env:
        - name: HOST
          value: "0.0.0.0"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: q4-server
spec:
  selector:
    app: q4-serverr
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP

