apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: q5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: q5
  template:
    metadata:
      labels:
        app: q5
    spec:
      containers:
      - name: my-container
        image: hwchiu/sre:q5
        imagePullPolicy: Always
        volumeMounts:
        - name: my-volume
          mountPath: /data
        env:
        - name: DATA_PATH
          value: "/data/"

  volumeClaimTemplates:
  - metadata:
      name: my-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi 
