apiVersion: apps/v1
kind: Deployment
metadata:
  name: q10-client
  labels:
    app: q10
spec:
  replicas: 2
  selector:
    matchLabels:
      app: q10
  template:
    metadata:
      labels:
        app: q10
    spec:
      containers:
      - name: app
        image: hwchiu/sre:q10-client
        imagePullPolicy: Always
        env:
        - name: HOST
          value: "q10-server"
        - name: PORT
          value: "80"
