helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm upgrade --install --create-namespace -n monitoring prom prometheus-community/kube-prometheus-stack --version=58.0.0 -f custom.yaml
